### ISSUE TITLE
[NumberGuesser] StringBuidler

### ISSUE THREAD

**Issue by pavel-b-novikov** [lim0nishe/nsudotnet#2]
Мне не совсем понятна логика. Вы создает SB, понятно. Вы пишете в него всякую информацию об игре. Построчно. Странно, но тоже понятно. При том вместо AppendLine ипользуете Append с переносом строки. Уже потихоньку становится непонятно. Потом вы выводите его на консоль, и спокойно дописываете уже в консоль оставшиеся данные. 
Вопрос - а SB-то зачем создавали? :) Это не то чтобы ошибка, просто очень странная логика.

**Comment by lim0nishe** [comment]
изначально создавал, потому что боялся сделать много конкатенаций строк. Сейчас сам долго не мог понять, что мною двигало, видимо просто мысль дальше пошла и я забыл про SB. Убрал его
