### ISSUE TITLE
[Rss2Email] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [lim0nishe/nsudotnet#3]
У вас много что не диспозится. Просмотрите внимательно что и где, и мне сюда отчитайтесь

**Comment by lim0nishe** [comment]
задиспозил таймер и стрим в RSSListener, SmtpClient в Messager

**Comment by pavel-b-novikov** [comment]
Вы как-то диспозить не научились правильно за семестр. Оберните в соответствующую синтаксическую конструкцию.

**Comment by lim0nishe** [comment]
обернул в блоки using
