### ISSUE TITLE
[Rss2Email] Сериализация

### ISSUE THREAD

**Issue by pavel-b-novikov** [lim0nishe/nsudotnet#4]
Что у вас за тяга к мазохизму и использованию XmlStreamReader/Writer. Сделайте блин по-человечески, на Xml-атрибутах (гугл поможет)

**Comment by lim0nishe** [comment]
не совсем понял, надо использовать XmlSerializer и реализовать интерфейс IXmlSerializable у себя в классах?

**Comment by pavel-b-novikov** [comment]
http://lmgtfy.com/?q=.net+xml+serialization+attributes

**Comment by lim0nishe** [comment]
переделал

**Comment by pavel-b-novikov** [comment]
Не не не. Делать отдельный itemSerializer нет необходимости. Пожалуйста, сделайте поддержку коллекций. Ну т.е. чтобы внутри Channel-а был массив item-ов

**Comment by lim0nishe** [comment]
Я думал над этим, просто в RSS канале на ленте item-ы записаны не в отдельное поле items, например, а просто накиданы в channel. Сериализатор разве поймет такое?

**Comment by pavel-b-novikov** [comment]
Поймет, если его правильно настроить. 
Впрочем ладно. По текущей статистике у вас набирается на трояк. Зачем плодить бесполезную работу - оставляйте.
